---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: mysql
  :database: bike_contest
  :username: merb
  :password: merb_bc

:test:
  <<: *defaults

:production:
  <<: *defaults
